---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: www-prod

labels:
  - pairs:
      app.kubernetes.io/instance: tbnl-prod
    includeSelectors: true
    includeTemplates: true

patchesStrategicMerge:
- version.yaml

