apiVersion: v1
kind: ConfigMap
metadata:
  name: www-nginx
data:
  # Based on config of nginx:1.25.4-alpine
  # /etc/nginx/conf.d/default.conf
  default.conf: |
    server {
      listen       80;
      listen  [::]:80;
      server_name  localhost;

      #access_log  /var/log/nginx/host.access.log  main;

      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }

      error_page  404              /404.html;

      # redirect server error pages to the static page /50x.html
      #
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }

      # Proxy old site to separate service
      #
      location /anno2003 {
          rewrite ^/anno2003(.*)$ $1 last;
          proxy_pass   http://www-2003;
      }

      # @TODO 
      # - cache headers
      # - small local cache
      # - only allowing specific urls and GET to www-2003
    }
