apiVersion: apps/v1
kind: Deployment
metadata:
  name: www
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    spec:
      containers:
        - name: www
          image: ghcr.io/tbeijen/tbnl-hugo:sha-aea4500
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              readOnly: true
          resources:
            requests:
              memory: "15Mi"
      volumes:
        - name: nginx-config
          configMap:
            name: www-nginx
