apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap.yaml
- deployment.yaml
- service.yaml

labels:
  - pairs:
      app.kubernetes.io/component: www
    includeSelectors: true
    includeTemplates: true
