---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: www-test

labels:
  - pairs:
      app.kubernetes.io/instance: tbnl-test
    includeSelectors: true
    includeTemplates: true

patchesStrategicMerge:
- replicas.yaml
- version.yaml
