apiVersion: apps/v1
kind: Deployment
metadata:
  name: www-2003
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: www
          image: tbeijen/tbnl-2003:1.0.0
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              memory: 100Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 200m
          readinessProbe:
            httpGet:
              path: /images/home.gif
              port: http
            initialDelaySeconds: 5
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 5