apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- www
- www-2003

namePrefix: "tbnl-"

labels:
  - pairs:
      app.kubernetes.io/name: tbnl
      app.kubernetes.io/instance: tbnl
    includeSelectors: true
    includeTemplates: true