apiVersion: v1
kind: Service
metadata:
  name: www-2003
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: www-2003
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: www
          image: tbeijen/tbnl-2003:1.0.0
          ports:
            - name: http
              containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"  
          # readinessProbe:
          #   httpGet:
          #     path: /left.php?pageId=1
          #     port: http
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          #   successThreshold: 1
          #   failureThreshold: 5