apiVersion: v1
kind: Service
metadata:
  name: www
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: www
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    spec:
      containers:
        - name: www
          image: ghcr.io/tbeijen/tbnl-hugo:sha-b52664a
          ports:
            - name: http
              containerPort: 80
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "200m"
